Remove unused variable, and fix some narrowing stuff.
src/multiint.cpp:404:52: error: narrowing conversion of ‘(rand() % 256)’ from ‘int’ to ‘char’ inside { } is ill-formed in C++11 [-Werror=narrowing]

Fixes #3552.