Use `#ifdef DEBUG` instead of `#if DEBUG`
Depending on settings / compiler, `#if DEBUG` can result in a compiler error.
(Example: `fatal error C1017: invalid integer constant expression`)

Use `#ifdef DEBUG` instead.