Reorder libs to fix linker error
libsdl.a requires UTF8toUTF32 from libframework.a.
Libraries which need symbols go first then the libraries
that resolve the symbols.

Fixes:
../lib/sdl/libsdl.a(main_sdl.o): In function `inputhandleText(SDL_TextInputEvent*)':
lib/sdl/main_sdl.cpp:1108: undefined reference to `UTF8toUTF32(char const*, unsigned int*)'