lib/wzmaplib: add missing `<cstdint>` includes
Without the change the build on upcoming `gcc-15` fails as:

    In file included from /build/warzone2100/lib/wzmaplib/src/map_script.cpp:20:
    /build/warzone2100/lib/wzmaplib/src/map_script.h:31:97: error: 'uint32_t' has not been declared
       31 | std::shared_ptr<Map> runMapScript(const std::vector<char>& fileBuffer, const std::string &path, uint32_t seed, bool preview, LoggingProtocol* pCustomLogger = nullptr);
          |                                                                                                 ^~~~~~~~